# ARRRRR! I'm a pirate and I care not for ye superficial conventions!
Layout/Tab:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_ignore
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/AccessModifierIndentation: #buggy: prepends an unecessary space
  Enabled: false
Layout/ClosingParenthesisIndentation: #buggy: misaligns
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
